name: CI/CD Pipeline
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install ruff 

      - name: Run linter Ruff
        run: ruff check .

      - name: Run Pytest Tests
        env:
          SECRET_KEY: "super_secret_dummy_key_for_github_actions_12345"  
        run: pytest tests/ -v



